const tabCategories = {
  Work: [
    'github', 'gitlab', 'bitbucket', 'jira', 'asana', 'trello',
    'microsoft teams', 'slack', 'zoom', 'notion', 'google docs',
    'dropbox', 'box', 'sharepoint', 'basecamp', 'confluence',
    'microsoft office', 'google drive', 'microsoft onedrive', 'evernote',
    'airtable', 'wrike', 'quip', 'huddle', 'Monday.com',
    'clockify', 'zoominfo', 'hubspot', 'salesforce', 'mailchimp',
    'zapier', 'linkedin', 'workplace', 'microsoft project',
    'canva', 'figma', 'adobe creative cloud', 'proofhub', 'xero',
    'freshbooks', 'quickbooks', 'zapier', 'appfolio', 'hubstaff',
    'notarize', 'procore', 'autodesk', 'salesforce', 'pipedrive',
    'toggl', 'cloudapp', 'smartsheet', 'google calendar', 'eventbrite',
    'meetup', 'eventzilla', 'moodle', 'coggle', 'lucidchart',
    'gitkraken', 'sonarqube', 'coda', 'miro', 'fivetran',
    'intercom', 'whatsapp for business', 'google sheets', 'sprout social',
    'clickup', 'teamviewer', 'kaltura', 'gotomeeting', 'wunderlist',
    'bitly', 'mailgun', 'help scout', 'freshservice', 'jira service desk',
    'servicenow', 'zendesk', 'sentry', 'atlassian', 'microsoft planner',
    'pivotal tracker', 'hello sign', 'teamgantt', '1password', 'LastPass',
  ],
  Social: [
    'facebook', 'twitter', 'instagram', 'linkedin', 'snapchat',
    'tiktok', 'pinterest', 'tumblr', 'reddit', 'whatsapp',
    'discord', 'youtube', 'vimeo', 'flickr', 'twitch',
    'quora', 'meetup', 'nextdoor', 'periscope', 'myspace',
    'badoo', 'okcupid', 'hinge', 'tinder', 'grindr',
    'skype', 'yelp', 'tripadvisor', 'tumblr', 'foursquare',
    'beacon', 'wattpad', 'last.fm', 'goodreads', 'soundcloud',
    'vk', 'wechat', 'line', 'telegram', 'clubhouse',
    'medium', 'blogger', 'wordpress', 'substack', 'bloglovin',
    'hacker news', 'mixer', 'fandom', 'dailymotion', 'photobucket',
    'snapfish', 'meetme', 'socialrank', 'allrecipes', 'food52',
  ],
  Research: [
    'google', 'wikipedia', 'researchgate', 'arxiv', 'pubmed',
    'sciencedirect', 'jstor', 'mendeley', 'springer', 'ieee',
    'doi.org', 'nature.com', 'plos', 'google scholar', 'cambridge.org',
    'tandfonline', 'elsevier', 'academic.oup.com', 'researcher',
    'citeseerx', 'worldcat', 'librarything', 'openlibrary', 'archive.org',
    'bookboon', 'bookfinder', 'z-lib', 'ssrn', 'bioRxiv',
    'arXiv', 'osf.io', 'researchmap', 'worldscientific', 'frontiersin',
    'mdpi', 'retractionwatch', 'researchgate.net', 'openedition', 'sagepub',
    'bmc', 'wiley', 'taylorandfrancis.com', 'journals.sagepub.com', 'plosone',
    'jstor.org', 'scopus', 'informe', 'science.gov', 'agris',
    'nationalgeographic.com', 'nasa.gov', 'fedstats.gov', 'usgs.gov', 'europa.eu',
    'data.gov', 'statista', 'openAI',
  ],
};

export default tabCategories;
